name: teste_esig
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  mobx: ^2.2.3
  flutter_mobx: ^2.2.0+1
  cupertino_icons: ^1.0.2
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
